### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Hkshab** [worldcoin/world-id-sign-in#61]
Many worldcoin user not able to restore their account if once they delete the application

**Comment by gatleas17** [comment]
I can't recover my account. I've been trying by all means for days, neither the orbe nor technical support (?) Neither my backups in iCloud, my proof of ownership, identifying myself through external applications it recovers me I'm too sad because I did love and protect the project, and I see verified people who use this beauty called orbe in a bad way, I even went to talk nice to the orb because inside me he tells me that if he listens to me hahaha even if it sounds silly well I already gave up goodbye worldcoin ;(

**Comment by andy-t-wang** [comment]
Hi please reach out to support. This is a separate service
